# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
     - "SergiiKram"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
     - "SergiiKram"
  - package-ecosystem: "docker"
    directory: "/src/ActivityWorker"
    ignore:
     - dependency-name: "dotnet/sdk"
       update-types: ["version-update:semver-major"]
     - dependency-name: "dotnet/aspnet"
       update-types: ["version-update:semver-major"]
    schedule:
      interval: "daily"
    assignees:
     - "SergiiKram"
  - package-ecosystem: "docker"
    directory: "/src/E2eTests"
    ignore:
     - dependency-name: "dotnet/sdk"
       update-types: ["version-update:semver-major"]
    schedule:
      interval: "daily"
    assignees:
     - "SergiiKram"
  - package-ecosystem: "docker"
    directory: "/src/Orchestrator"
    ignore:
     - dependency-name: "dotnet/sdk"
       update-types: ["version-update:semver-major"]
     - dependency-name: "dotnet/aspnet"
       update-types: ["version-update:semver-major"]
    schedule:
      interval: "daily"
    assignees:
     - "SergiiKram"
  - package-ecosystem: "docker"
    directory: "/src/Orchestrator.UnitTests"
    ignore:
     - dependency-name: "dotnet/sdk"
       update-types: ["version-update:semver-major"]
    schedule:
      interval: "daily"
    assignees:
     - "SergiiKram"
