version: '3.4'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
     - "5432:5432"
    volumes:
     - orchestrator-database:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - orchestrator-redis:/data

  rabbitmq:
    image: rabbitmq:management
    hostname: 'rabbitmq'
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - orchestrator-rabbitmq:/var/lib/rabbitmq

volumes:
  orchestrator-redis:
    external: false
  orchestrator-database:
    external: false
  orchestrator-rabbitmq:
    external: false
