version: '3.4'

services:
  orchestrator:
    image: ${DOCKER_REGISTRY-}orchestrator
    build:
      context: .
      dockerfile: Orchestrator/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "7080:80"
    depends_on:
     - postgres
     - redis
     - rabbitmq

  activityworker:
    image: ${DOCKER_REGISTRY-}activityworker
    build:
      context: .
      dockerfile: ActivityWorker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "7180:80"
    depends_on:
     - rabbitmq
