version: '3.4'

services:
  postgres:
    image: postgres

  redis:
    image: redis

  rabbitmq:
    image: rabbitmq:management

  orchestrator:
    image: ${DOCKER_REGISTRY-}orchestrator
    build:
      context: .
      dockerfile: Orchestrator/Dockerfile
    depends_on:
     - postgres
     - redis
     - rabbitmq

  activityworker:
    image: ${DOCKER_REGISTRY-}activityworker
    build:
      context: .
      dockerfile: ActivityWorker/Dockerfile
    depends_on:
     - rabbitmq
