version: '3.4'

services:
  postgres:
    environment:
      POSTGRES_PASSWORD: password
    ports:
     - "5432:5432"
    volumes:
     - orchestrator-database:/var/lib/postgresql/data

  redis:
    ports:
      - "6379:6379"
    volumes:
      - orchestrator-redis:/data

  rabbitmq:
    hostname: 'rabbitmq'
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - orchestrator-rabbitmq:/var/lib/rabbitmq

  orchestrator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "7080:80"

  activityworker:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "7180:80"

volumes:
  orchestrator-redis:
    external: false
  orchestrator-database:
    external: false
  orchestrator-rabbitmq:
    external: false
