name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      working-directory: src
      run: dotnet restore OrchestrationTests.sln
    - name: Build
      working-directory: src
      run: dotnet build OrchestrationTests.sln --configuration Release --no-restore
    - name: Test
      working-directory: src
      run: dotnet test OrchestrationTests.sln --configuration Release --no-build --verbosity normal
